services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  api:
    build:
      context: ../..
      dockerfile: ./config/dev/Dockerfile
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: deno task run

volumes:
  postgres_data: